### ISSUE TITLE
invalid syntax for both sankey and sunburst charts!

### ISSUE THREAD

**Issue by datalake101** [asjadnaqvi/stata-sunburst#1]
. net install sunburst, from("https://raw.githubusercontent.com/asjadnaqvi/stata-sunburst/
> main/installation/") replace
checking sunburst consistency and verifying not already installed...
installing into /Users/ghosebishwajit/Library/Application Support/Stata/ado/plus/...
installation complete.

. use "https://github.com/asjadnaqvi/stata-sunburst/blob/main/data/sunburst.dta?raw=true",
>  clear

. sunburst value, by(continent)
invalid syntax
r(198);

**Comment by asjadnaqvi** [comment]
This error is mostly likely linked to `palettes` and `colrspace` not being updated.

Check for these:
```
ado update palettes
ado update colrspace
```

and try rerunning the command again.
